; PlatformIO Project Configuration File
;
; DualShock 3 (PS3) Controller interface for ESP32
; See: https://github.com/jvpernis/esp32-ps3

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/jvpernis/esp32-ps3
